name: Bug report
description: Report a problem to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the behavior.
      placeholder: 1) Go to..., 2) Click..., 3) See error...
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: Context
      description: Repo/link or environment info (if applicable)
      placeholder: e.g. repo name, branch, OS/browser
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste logs or add screenshots to help explain.

